import pyperclip
from db_connector import *
t = """
(1, "Editing a React component in Visual Studio Code", "Coding", "RandomString188")
(1, "Google Meet call titled 'Intro to Web Development'", "Meeting", "RandomString189")
(1, "Reading a blog post about Node.js best practices", "Browsing", "RandomString190")
(1, "Slack discussion about version control with Git", "Communicating", "RandomString191")
(1, "Reviewing a pull request on GitHub", "Browsing", "RandomString192")
(2, "Visual Studio Code open with a Python script for data analysis", "Coding", "RandomString193")
(2, "Zoom meeting about database optimization techniques", "Meeting", "RandomString194")
(2, "Online tutorial about machine learning with TensorFlow", "Browsing", "RandomString195")
(2, "Writing an email about software deployment strategies", "Communicating", "RandomString196")
(2, "Browsing Stack Overflow for solutions to a coding error", "Browsing", "RandomString197")
(3, "Developing a mobile app in Android Studio", "Coding", "RandomString198")
(3, "Microsoft Teams meeting for project planning", "Meeting", "RandomString199")
(3, "Reading online documentation for Swift programming", "Browsing", "RandomString200")
(3, "Chatting about UI design trends in a Telegram group", "Communicating", "RandomString201")
(3, "Exploring an online course on cybersecurity", "Browsing", "RandomString202")
(4, "Coding a server script in Node.js on Visual Studio Code", "Coding", "RandomString203")
(4, "Attending a webinar on cloud infrastructure", "Meeting", "RandomString204")
(4, "Looking at a tech news site for the latest in tech startups", "Browsing", "RandomString205")
(4, "Discussing agile project management on Slack", "Communicating", "RandomString206")
(4, "Researching Docker containers on a tech forum", "Browsing", "RandomString207")
(5, "Working on an SQL query for database reporting", "Coding", "RandomString208")
(5, "Google Hangouts session about remote team collaboration", "Meeting", "RandomString209")
(5, "Reading an article about the future of artificial intelligence", "Browsing", "RandomString210")
(5, "Email conversation about integrating third-party APIs", "Communicating", "RandomString211")
(5, "Online search for the best IDEs for Python development", "Browsing", "RandomString212")
(6, "Refactoring JavaScript code in Visual Studio Code", "Coding", "RandomString213")
(6, "Participating in a Discord Q&A session about web development", "Meeting", "RandomString214")
(6, "Reading reviews on the latest programming books", "Browsing", "RandomString215")
(6, "Slack chat about deploying apps to the Apple App Store", "Communicating", "RandomString216")
(6, "Browsing GitHub for open source projects to contribute to", "Browsing", "RandomString217")
(6, "The user is viewing a Git repository on GitHub", "Browsing", "RandomString97")
(6, "Visual Studio Code is open with a file named 'data_analysis.py'", "Coding", "RandomString98")
(6, "A Zoom meeting titled 'Python Development Discussion' is ongoing", "Meeting", "RandomString99")
(6, "The user is browsing through Python documentation on a web browser", "Browsing", "RandomString100")
(6, "Slack is open, showing a conversation about bug fixes in 'hello_world.py'", "Communicating", "RandomString101")
(7, "Visual Studio Code displays a project named 'user_interface_design'", "Coding", "RandomString102")
(7, "Google Meet shows a brainstorming session titled 'New Project Ideas'", "Meeting", "RandomString103")
(7, "The user is reading a technical blog about advanced Python features", "Browsing", "RandomString104")
(7, "An email draft is open, discussing plans for a new Python module", "Communicating", "RandomString105")
(7, "The user is reviewing a Jupyter Notebook file named 'data_visualization.ipynb'", "Coding", "RandomString106")
(8, "A Microsoft Teams call titled 'Front-End Development Sync-Up' is in session", "Meeting", "RandomString107")
(8, "Visual Studio Code shows a JavaScript file named 'app.js'", "Coding", "RandomString108")
(8, "The user is participating in a coding challenge on HackerRank", "Browsing", "RandomString109")
(8, "The user is in a chat on Discord, discussing JavaScript frameworks", "Communicating", "RandomString110")
(8, "A Python script named 'data_parser.py' is open in Visual Studio Code", "Coding", "RandomString111")
(9, "Zoom is open with a workshop titled 'Advanced Programming Techniques'", "Meeting", "RandomString112")
(9, "The user is editing a CSS file in Visual Studio Code for website styling", "Coding", "RandomString113")
(9, "Browsing a tech news site for the latest updates in software development", "Browsing", "RandomString114")
(9, "An email conversation about web design trends is visible", "Communicating", "RandomString115")
(9, "The user is working on a SQL database script in Visual Studio Code", "Coding", "RandomString116")
(10, "Microsoft Teams shows a meeting titled 'UI/UX Design Review'", "Meeting", "RandomString117")
(10, "Browsing an online course catalog for web development classes", "Browsing", "RandomString118")
(10, "Slack shows a discussion about integrating APIs in a web application", "Communicating", "RandomString119")
(10, "The user is creating a React component in Visual Studio Code", "Coding", "RandomString120")
(10, "A web browser is open on a page about cloud computing basics", "Browsing", "RandomString121")
(10, "The user is reviewing pull requests on GitHub", "Browsing", "RandomString122")
(10, "Visual Studio Code is open with 'database_config.sql'", "Coding", "RandomString123")
(11, "A Microsoft Teams meeting titled 'Project Roadmap Discussion' is in progress", "Meeting", "RandomString124")
(11, "The user is on a tech forum, reading a thread about cloud service optimizations", "Browsing", "RandomString125")
(11, "Slack is open with ongoing discussions about API integration strategies", "Communicating", "RandomString126")
(11, "The user is debugging a JavaScript file in Visual Studio Code", "Coding", "RandomString127")
(11, "Google Meet shows a training session on machine learning applications", "Meeting", "RandomString128")
(11, "The user is on LinkedIn, browsing through posts on software development trends", "Browsing", "RandomString129")
(12, "An email to a project manager about upcoming release schedules is being composed", "Communicating", "RandomString130")
(12, "Visual Studio Code shows 'user_authentication_module.py' being edited", "Coding", "RandomString131")
(12, "Zoom call in progress with a title 'Agile Methodologies Workshop'", "Meeting", "RandomString132")
(12, "The user is reading a digital book titled 'Advanced Python Programming'", "Browsing", "RandomString133")
(12, "Slack shows a conversation planning the next sprint activities", "Communicating", "RandomString134")
(12, "The user is working on an HTML template for a web application in Visual Studio Code", "Coding", "RandomString135")
(13, "Microsoft Teams displays a discussion on UI testing protocols", "Meeting", "RandomString136")
(13, "The user is browsing a subreddit dedicated to web development", "Browsing", "RandomString137")
(13, "An ongoing chat on Telegram with a developer community is visible", "Communicating", "RandomString138")
(13, "Visual Studio Code is open with a Ruby script 'data_migration.rb'", "Coding", "RandomString139")
(13, "A Google Meet session is titled 'Cross-Platform Development Insights'", "Meeting", "RandomString140")
(13, "The user is researching NoSQL databases on a tech blog", "Browsing", "RandomString141")
(14, "Drafting an email query about cloud hosting solutions", "Communicating", "RandomString142")
(14, "Working on a C# application in Visual Studio Code", "Coding", "RandomString143")
(14, "Participating in a virtual conference on cybersecurity", "Meeting", "RandomString144")
(14, "The user is on a Q&A site, looking up questions on network security", "Browsing", "RandomString145")
(14, "A conversation about data encryption methods is ongoing in Slack", "Communicating", "RandomString146")
(6, "The user is viewing a Git repository on GitHub", "Browsing", "RandomString97")
(6, "Visual Studio Code is open with a file named 'data_analysis.py'", "Coding", "RandomString98")
(6, "A Zoom meeting titled 'Python Development Discussion' is ongoing", "Meeting", "RandomString99")
(6, "The user is browsing through Python documentation on a web browser", "Browsing", "RandomString100")
(6, "Slack is open, showing a conversation about bug fixes in 'hello_world.py'", "Communicating", "RandomString101")
(7, "Visual Studio Code displays a project named 'user_interface_design'", "Coding", "RandomString102")
(7, "Google Meet shows a brainstorming session titled 'New Project Ideas'", "Meeting", "RandomString103")
(7, "The user is reading a technical blog about advanced Python features", "Browsing", "RandomString104")
(7, "An email draft is open, discussing plans for a new Python module", "Communicating", "RandomString105")
(7, "The user is reviewing a Jupyter Notebook file named 'data_visualization.ipynb'", "Coding", "RandomString106")
(8, "A Microsoft Teams call titled 'Front-End Development Sync-Up' is in session", "Meeting", "RandomString107")
(8, "Visual Studio Code shows a JavaScript file named 'app.js'", "Coding", "RandomString108")
(8, "The user is participating in a coding challenge on HackerRank", "Browsing", "RandomString109")
(8, "The user is in a chat on Discord, discussing JavaScript frameworks", "Communicating", "RandomString110")
(8, "A Python script named 'data_parser.py' is open in Visual Studio Code", "Coding", "RandomString111")
(9, "Zoom is open with a workshop titled 'Advanced Programming Techniques'", "Meeting", "RandomString112")
(9, "The user is editing a CSS file in Visual Studio Code for website styling", "Coding", "RandomString113")
(9, "Browsing a tech news site for the latest updates in software development", "Browsing", "RandomString114")
(9, "An email conversation about web design trends is visible", "Communicating", "RandomString115")
(9, "The user is working on a SQL database script in Visual Studio Code", "Coding", "RandomString116")
(10, "Microsoft Teams shows a meeting titled 'UI/UX Design Review'", "Meeting", "RandomString117")
(10, "Browsing an online course catalog for web development classes", "Browsing", "RandomString118")
(10, "Slack shows a discussion about integrating APIs in a web application", "Communicating", "RandomString119")
(10, "The user is creating a React component in Visual Studio Code", "Coding", "RandomString120")
(10, "A web browser is open on a page about cloud computing basics", "Browsing", "RandomString121")
These data points continue the theme of coding, browsing, communicating, and attending meetings, with a focus on software development activities and various technologies.
(10, "The user is reviewing pull requests on GitHub", "Browsing", "RandomString122")
(10, "Visual Studio Code is open with 'database_config.sql'", "Coding", "RandomString123")
(11, "A Microsoft Teams meeting titled 'Project Roadmap Discussion' is in progress", "Meeting", "RandomString124")
(11, "The user is on a tech forum, reading a thread about cloud service optimizations", "Browsing", "RandomString125")
(11, "Slack is open with ongoing discussions about API integration strategies", "Communicating", "RandomString126")
(11, "The user is debugging a JavaScript file in Visual Studio Code", "Coding", "RandomString127")
(11, "Google Meet shows a training session on machine learning applications", "Meeting", "RandomString128")
(11, "The user is on LinkedIn, browsing through posts on software development trends", "Browsing", "RandomString129")
(12, "An email to a project manager about upcoming release schedules is being composed", "Communicating", "RandomString130")
(12, "Visual Studio Code shows 'user_authentication_module.py' being edited", "Coding", "RandomString131")
(12, "Zoom call in progress with a title 'Agile Methodologies Workshop'", "Meeting", "RandomString132")
(12, "The user is reading a digital book titled 'Advanced Python Programming'", "Browsing", "RandomString133")
(12, "Slack shows a conversation planning the next sprint activities", "Communicating", "RandomString134")
(12, "The user is working on an HTML template for a web application in Visual Studio Code", "Coding", "RandomString135")
(13, "Microsoft Teams displays a discussion on UI testing protocols", "Meeting", "RandomString136")
(13, "The user is browsing a subreddit dedicated to web development", "Browsing", "RandomString137")
(13, "An ongoing chat on Telegram with a developer community is visible", "Communicating", "RandomString138")
(13, "Visual Studio Code is open with a Ruby script 'data_migration.rb'", "Coding", "RandomString139")
(13, "A Google Meet session is titled 'Cross-Platform Development Insights'", "Meeting", "RandomString140")
(13, "The user is researching NoSQL databases on a tech blog", "Browsing", "RandomString141")
(14, "Drafting an email query about cloud hosting solutions", "Communicating", "RandomString142")
(14, "Working on a C# application in Visual Studio Code", "Coding", "RandomString143")
(14, "Participating in a virtual conference on cybersecurity", "Meeting", "RandomString144")
(14, "The user is on a Q&A site, looking up questions on network security", "Browsing", "RandomString145")
(14, "A conversation about data encryption methods is ongoing in Slack", "Communicating", "RandomString146")
These additional data points maintain a consistent structure and theme, focusing on diverse software development tasks, online communication, and learning activities.
(14, "Visual Studio Code is open, showing a Dockerfile being edited", "Coding", "RandomString147")
(14, "Zoom call in progress with a session titled 'Introduction to Docker'", "Meeting", "RandomString148")
(15, "Browsing an article about microservices architecture", "Browsing", "RandomString149")
(15, "Composing an email to a team member about containerization strategies", "Communicating", "RandomString150")
(15, "In Visual Studio Code, working on a script 'server_setup.sh'", "Coding", "RandomString151")
(15, "Google Meet showing a team stand-up meeting discussing current project status", "Meeting", "RandomString152")
(15, "Reading a forum post about continuous integration/continuous deployment (CI/CD) practices", "Browsing", "RandomString153")
(15, "Slack conversation about setting up a new development environment", "Communicating", "RandomString154")
(16, "Editing a React Native app component in Visual Studio Code", "Coding", "RandomString155")
(16, "Participating in a webinar titled 'Cross-Platform Mobile Development'", "Meeting", "RandomString156")
(16, "Looking up the latest React Native updates on a tech news site", "Browsing", "RandomString157")
(16, "Messaging a colleague about mobile app design ideas on Microsoft Teams", "Communicating", "RandomString158")
(16, "Visual Studio Code shows a Python script for data scraping", "Coding", "RandomString159")
(16, "Zoom meeting with a client to discuss app development requirements", "Meeting", "RandomString160")
(17, "Researching data scraping techniques on a programming blog", "Browsing", "RandomString161")
(17, "Emailing a data analyst about potential data sources for a project", "Communicating", "RandomString162")
(17, "Writing a Java program in Visual Studio Code for system automation", "Coding", "RandomString163")
(17, "Microsoft Teams meeting titled 'Automation Project Kick-off'", "Meeting", "RandomString164")
(17, "Looking at an online course for advanced Java programming", "Browsing", "RandomString165")
(17, "Discussing project timelines on Slack with the project manager", "Communicating", "RandomString166")
(18, "Developing a Node.js API in Visual Studio Code", "Coding", "RandomString167")
(18, "Google Meet session about RESTful API design best practices", "Meeting", "RandomString168")
(18, "Reading a Stack Overflow thread on Node.js performance optimization", "Browsing", "RandomString169")
(18, "Sending a message on Discord about troubleshooting an API issue", "Communicating", "RandomString170")
(18, "Working on an Angular project in Visual Studio Code", "Coding", "RandomString171")
(18, "Zoom workshop on modern front-end frameworks", "Meeting", "RandomString172")
(19, "Browsing a tutorial on Angular routing and state management", "Browsing", "RandomString173")
(19, "Drafting an email about front-end development challenges", "Communicating", "RandomString174")
(19, "Visual Studio Code is open with a file 'cloud_config.yaml'", "Coding", "RandomString175")
(19, "Participating in a Microsoft Teams call about cloud infrastructure planning", "Meeting", "RandomString176")
(19, "Reading articles about AWS and Azure cloud services", "Browsing", "RandomString177")
(19, "Slack discussion on choosing the right cloud provider for a project", "Communicating", "RandomString178")
(20, "Editing a Bash script in Visual Studio Code for server automation", "Coding", "RandomString179")
(20, "Google Meet training session on Linux server management", "Meeting", "RandomString180")
(20, "Exploring forums for Linux server troubleshooting", "Browsing", "RandomString181")
(20, "Messaging a sysadmin on Telegram about server configuration issues", "Communicating", "RandomString182")
(20, "Working in Visual Studio Code on a Python data analysis script", "Coding", "RandomString183")
(20, "Zoom call discussing data analysis project scope with the team", "Meeting", "RandomString184")
(14, "Editing a Dockerfile in Visual Studio Code for container setup", "Coding", "RandomString147")
(14, "Zoom meeting titled 'Frontend vs Backend Technologies'", "Meeting", "RandomString148")
(15, "Browsing an online course on React Native development", "Browsing", "RandomString149")
(15, "Google Meet call with a client discussing app requirements", "Meeting", "RandomString150")
(15, "Writing a blog post about new JavaScript features in Visual Studio Code", "Coding", "RandomString151")
(15, "Email exchange with a colleague about code review feedback", "Communicating", "RandomString152")
(15, "Online research on the latest Android SDK updates", "Browsing", "RandomString153")
(16, "Slack conversation about deploying apps on AWS", "Communicating", "RandomString154")
(16, "Visual Studio Code is open with a TypeScript project", "Coding", "RandomString155")
(16, "Attending a webinar on Kubernetes and cloud orchestration", "Meeting", "RandomString156")
(16, "Reviewing a tech article on machine learning algorithms", "Browsing", "RandomString157")
(16, "Composing an email about a potential software partnership", "Communicating", "RandomString158")
(17, "Planning a database schema in Visual Studio Code", "Coding", "RandomString159")
(17, "Microsoft Teams meeting about API design principles", "Meeting", "RandomString160")
(17, "Reading a whitepaper on blockchain technology", "Browsing", "RandomString161")
(17, "Discussing project milestones over Skype", "Communicating", "RandomString162")
(17, "Online tutorial for advanced SQL queries", "Browsing", "RandomString163")
(18, "Zoom call for a Python coding bootcamp", "Meeting", "RandomString164")
(18, "Writing automated test scripts in Visual Studio Code", "Coding", "RandomString165")
(18, "Slack chat about troubleshooting server issues", "Communicating", "RandomString166")
(18, "Researching best practices for UX design", "Browsing", "RandomString167")
(18, "Drafting a project proposal email for a new app", "Communicating", "RandomString168")
(19, "Developing a Flutter app in Visual Studio Code", "Coding", "RandomString169")
(19, "Participating in an online tech hackathon", "Meeting", "RandomString170")
(19, "Exploring articles on augmented reality in web development", "Browsing", "RandomString171")
(19, "WhatsApp conversation regarding app release strategies", "Communicating", "RandomString172")
(19, "Video tutorial on advanced CSS techniques", "Browsing", "RandomString173")
(20, "Coding a chatbot in Python using Visual Studio Code", "Coding", "RandomString174")
(20, "Microsoft Teams call discussing remote work tools", "Meeting", "RandomString175")
(20, "Reading a forum post on agile vs waterfall methodologies", "Browsing", "RandomString176")
(20, "Emailing feedback on a recent code sprint", "Communicating", "RandomString177")
(20, "Learning about AI ethics on an online platform", "Browsing", "RandomString178")
"""

t = t.replace("(", "insert_batch_image_data(")
pyperclip.copy(t)


insert_batch_metadata("Dhruv Shah", "2023-11-15")
insert_batch_metadata("Dhruv Shah", "2023-11-16")
insert_batch_metadata("Dhruv Shah", "2023-11-17")
insert_batch_metadata("Dhruv Shah", "2023-11-18")
insert_batch_metadata("Dhruv Shah", "2023-11-19")
insert_batch_metadata("Ben Steele", "2023-11-15")
insert_batch_metadata("Ben Steele", "2023-11-16")
insert_batch_metadata("Ben Steele", "2023-11-17")
insert_batch_metadata("Ben Steele", "2023-11-18")
insert_batch_metadata("Ben Steele", "2023-11-19")
insert_batch_metadata("Ben Steele", "2023-11-19")
insert_batch_metadata("Matt Steele", "2023-11-15")
insert_batch_metadata("Matt Steele", "2023-11-16")
insert_batch_metadata("Matt Steele", "2023-11-17")
insert_batch_metadata("Matt Steele", "2023-11-18")
insert_batch_metadata("Matt Steele", "2023-11-19")
insert_batch_metadata("Tyler Kwok", "2023-11-15")
insert_batch_metadata("Tyler Kwok", "2023-11-16")
insert_batch_metadata("Tyler Kwok", "2023-11-17")
insert_batch_metadata("Tyler Kwok", "2023-11-18")
insert_batch_metadata("Tyler Kwok", "2023-11-19")



"""
2023-11-19
2023-11-18
2023-11-17
2023-11-16
2023-11-15
2023-11-14
2023-11-13
"""